[package]
name = "impact_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.14", features = ["derive"] }
paste = "1.0"

impact_ecs_macros = { path = "impact_ecs_macros" }
impact_utils = { path = "../impact_utils" }
