[advisories]
ignore = [
    { id = "RUSTSEC-2024-0436", reason = "some dependencies still use old paste crate" },
]

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0", "BSD-2-Clause", "CC0-1.0", "Zlib"]
