[package]
name = "impact"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["impact_ecs", "impact_ecs/impact_ecs_macros"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
approx = "0.5.1"
atomic_enum = "0.2.0"
bytemuck = { version = "1.4", features = ["derive"] }
cfg-if = "1"
const-fnv1a-hash = "1.0.1"
env_logger = "0.9"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
lazy_static = "1.4.0"
log = "0.4"
nalgebra = { version = "0.31.0", features = ["bytemuck"] }
num-traits = "0.2.15"
petgraph = { version = "0.6.2", default-features = false, features = ["graphmap"] }
pollster = "0.2"
raw-window-handle = "0.4.3"
simba = "0.7.1"
wgpu = "0.12"
winit = "0.26"

impact_ecs = { path = "impact_ecs" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Window", "Element"] }
wgpu = { version = "0.12", features = ["webgl"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.2"
