[package]
name = "impact_ecs"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
const-fnv1a-hash = { workspace = true }
inventory = { workspace = true }
paste = { workspace = true }

impact_containers = { path = "../impact_containers" }
impact_ecs_macros = { path = "impact_ecs_macros" }

[lints]
workspace = true
