[package]
name = "generate_roc"
description = "Template code generation tool for creating Roc language bindings"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "generate_roc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
roc_integration = { path = "<path to roc_integration>", features = ["cli"] }
target_crate = { package = "<target package name>", path = "<target package path>", features = [
    "roc_codegen",
] }
