[package]
name = "roc_impact"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
impact = { workspace = true }
roc_std = { workspace = true }

[lints]
workspace = true
