[package]
name = "impact_ecs_macros"
description = "Procedural macros for the Impact ECS library"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
proc-macro = true

[dependencies]
lazy_static = { workspace = true }
proc-macro2 = "1.0"
proc-macro-crate = "3.2"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }

[lints]
workspace = true
