[package]
name = "impact_log"
description = "Logging for the Impact engine"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
log = "0.4"

[lints]
workspace = true
