[package]
name = "roc_host_bin"
version = { workspace = true }
edition = { workspace = true }
description = "This crate wraps roc_host to build an executable. This executable is used by `roc preprocess-host ...`. That command generates an .rh and .rm file, these files are used by the [surgical linker](https://github.com/roc-lang/roc/tree/main/crates/linker#the-roc-surgical-linker)."

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
roc_host = { workspace = true }

[lints]
workspace = true
