pipeline {
    agent {
        dockerfile {
            dir 'engine/Jenkins'
        }
    }
    stages {
        stage('build') {
            steps {
                dir('engine') {
                    sh 'cargo build'
                }
            }
        }
        stage('build-release') {
            steps {
                dir('engine') {
                    sh 'cargo build --release'
                }
            }
        }
        stage('test') {
            steps {
                dir('engine') {
                    sh 'cargo test --all'
                }
            }
        }
        stage('test-asan') {
            steps {
                dir('engine') {
                    sh 'cargo clean'
                    sh 'RUSTFLAGS=-Zsanitizer=address cargo +nightly test --workspace --target x86_64-unknown-linux-gnu'
                }
            }
        }
        stage('test-miri') {
            steps {
                dir('engine') {
                    sh 'cargo clean'
                    sh 'PROPTEST_DISABLE_FAILURE_PERSISTENCE=1 PROPTEST_CASES=1 MIRIFLAGS=-Zmiri-disable-isolation cargo +nightly miri test --workspace'
                }
            }
        }
    }
    post{
        failure {
            emailext subject: '${DEFAULT_SUBJECT}',
                body: '${DEFAULT_CONTENT}',
                recipientProviders: [developers(), requestor()]

        }
    }
}
