[package]
name = "impact_ecs"
description = "Entity-Component-System library for the Impact game engine"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
arbitrary = ["dep:arbitrary"]
cli = ["dep:clap"]
flamegraph = ["profiling"]
profiling = ["impact_profiling"]
roc_codegen = ["roc_integration/roc_codegen"]

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
bytemuck = { workspace = true }
clap = { workspace = true, optional = true }
const-fnv1a-hash = { workspace = true }
fastrand = "2.3"
impact_containers = { path = "../impact_containers" }
impact_ecs_macros = { path = "impact_ecs_macros" }
impact_profiling = { path = "../impact_profiling", optional = true }
inventory = { workspace = true }
nohash-hasher = { workspace = true }
paste = { workspace = true }
roc_integration = { path = "../../../roc_integration" }

[lints]
workspace = true

[[bin]]
name = "impact_ecs"
path = "src/bin/impact_ecs.rs"
required-features = ["cli"]

[[bench]]
name = "entity"
harness = false
required-features = ["profiling"]

[[bench]]
name = "query"
harness = false
required-features = ["profiling"]
