[package]
name = "impact_texture"
description = "Texture management for the Impact engine"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
arbitrary = ["dep:arbitrary", "impact_math/arbitrary"]
bincode = ["dep:bincode", "serde"]
roc_codegen = ["dep:inventory", "roc_integration/roc_codegen"]
serde = ["dep:serde", "impact_gpu/serde", "impact_math/serde"]

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }
bytemuck = { workspace = true }
half = { version = "2.6", features = ["bytemuck"] }
impact_containers = { path = "../impact_containers" }
impact_gpu = { path = "../impact_gpu" }
impact_io = { path = "../impact_io", features = ["png", "jpeg"] }
impact_log = { path = "../impact_log" }
impact_math = { path = "../impact_math" }
impact_resource = { path = "../impact_resource" }
inventory = { workspace = true, optional = true }
roc_integration = { path = "../../../roc_integration" }
serde = { workspace = true, optional = true }

[lints]
workspace = true
