[package]
name = "impact_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.22", features = ["derive"] }
const-fnv1a-hash = "1.1"
lazy_static = "1.4"
num-traits = "0.2"
