[package]
name = "impact_utils"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
const-fnv1a-hash = "1.1"
lazy_static = "1.4"
num-traits = { workspace = true }

[lints]
workspace = true
