[package]
name = "generate_roc"
description = "Code generation tool for Roc language bindings in the headless Impact application"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "generate_roc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
roc_integration = { path = "../../../../roc_integration", features = ["cli"] }
target_crate = { package = "headless_app", path = "../..", features = [
    "roc_codegen",
] }
