[package]
name = "impact_dev_ui"
version = { workspace = true }
edition = { workspace = true }

[features]
arbitrary = ["dep:arbitrary"]
roc_codegen = ["dep:inventory", "roc_integration/roc_codegen"]

[dependencies]
anyhow = { workspace = true }
arbitrary = { version = "1.3", features = ["derive"], optional = true }
egui_extras = "0.31"
inventory = { workspace = true, optional = true }
impact = { path = ".." }
serde = { version = "1.0", features = ["derive"] }

roc_integration = { path = "../../roc_integration" }

[lints]
workspace = true
