[package]
name = "impact_ecs_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4"
proc-macro2 = "1.0"
proc-macro-crate = "3.2"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
