pipeline {
    agent {
        dockerfile {
            dir 'Jenkins'
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'cargo build'
            }
        }
        stage('build-release') {
            steps {
                sh 'cargo build --release'
            }
        }
        stage('test') {
            steps {
                sh 'cargo test --all'
            }
        }
        stage('test-release') {
            steps {
                sh 'cargo test --release --all'
            }
        }
        stage('test-miri') {
            steps {
                sh 'cargo clean'
                sh 'PROPTEST_CASES=1 MIRIFLAGS=-Zmiri-disable-isolation cargo +nightly miri test --all'
            }
        }
    }
    post{
        failure {
            emailext subject: '${DEFAULT_SUBJECT}',
                body: '${DEFAULT_CONTENT}',
                recipientProviders: [developers(), requestor()]
            
        }
    }
}