[package]
name = "impact_math"
version = { workspace = true }
edition = { workspace = true }

[features]
roc_codegen = ["dep:inventory", "roc_codegen/enabled"]

[dependencies]
bytemuck = { workspace = true }
const-fnv1a-hash = { workspace = true }
inventory = { workspace = true, optional = true }
lazy_static = { workspace = true }
num-traits = { workspace = true }

roc_codegen = { path = "../../roc_codegen" }

[lints]
workspace = true
