[package]
name = "impact_math"
version = { workspace = true }
edition = { workspace = true }

[features]
arbitrary = ["dep:arbitrary"]
roc_codegen = ["dep:inventory", "roc_integration/roc_codegen"]

[dependencies]
anyhow = { workspace = true }
arbitrary = { version = "1.3", features = ["derive"], optional = true }
bytemuck = { workspace = true }
const-fnv1a-hash = { workspace = true }
inventory = { workspace = true, optional = true }
lazy_static = { workspace = true }
num-traits = { workspace = true }

roc_integration = { path = "../../roc_integration" }

[lints]
workspace = true
