[package]
name = "roc_io_error"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = "Common functionality for Roc to interface with std::io::Error"

[dependencies]
roc_std = { workspace = true }

[lints]
workspace = true
