//! Meshes that should always be available.

use crate::{
    FrontFaceSide, TriangleMeshRegistry, import,
    setup::{BoxMesh, SphericalLightVolumeMesh, TriangleMeshTemplate},
};
use anyhow::Result;

/// Loads all builtin meshes into the registry.
pub fn load_builtin_meshes(registry: &mut TriangleMeshRegistry) -> Result<()> {
    for declaration_fn in [
        screen_filling_quad_mesh_declaration,
        spherical_light_volume_mesh_declaration,
        skybox_mesh_declaration,
    ] {
        import::load_declared_triangle_mesh(registry, &declaration_fn())?;
    }
    Ok(())
}

macro_rules! declare_builtin_triangle_mesh {
    (
        $(#[$id_meta:meta])*
        fn $id_fn_name:ident() => $desc:expr;

        $(#[$spec_meta:meta])*
        fn $declaration_fn_name:ident() => $template:expr;
    ) => {
        pastey::paste! {
            static [<$id_fn_name:upper>]: std::sync::LazyLock<$crate::TriangleMeshID> =
                std::sync::LazyLock::new(|| $crate::TriangleMeshID(impact_math::hash64!($desc)));

            $(#[$id_meta])*
            pub fn $id_fn_name() -> $crate::TriangleMeshID {
                *[<$id_fn_name:upper>]
            }

            $(#[$spec_meta])*
            fn $declaration_fn_name() -> $crate::import::TriangleMeshDeclaration {
                $crate::import::TriangleMeshDeclaration {
                    name: String::from($desc),
                    source: $crate::import::TriangleMeshSource::Template($template),
                    texture_projection: None,
                }
            }
        }
    };
}

declare_builtin_triangle_mesh! {
    /// The [`TriangleMeshID`](crate::TriangleMeshID) of a builtin mesh
    /// generated by
    /// [`TriangleMesh::create_screen_filling_quad`](crate::TriangleMesh::create_screen_filling_quad);
    fn screen_filling_quad_mesh_id() => "Screen filling quad mesh";

    fn screen_filling_quad_mesh_declaration() => TriangleMeshTemplate::ScreenFillingQuad;
}

declare_builtin_triangle_mesh! {
    /// The [`TriangleMeshID`](crate::TriangleMeshID) of a builtin mesh
    /// generated by
    /// [`TriangleMesh::create_spherical_light_volume`](crate::TriangleMesh::create_spherical_light_volume).
    fn spherical_light_volume_mesh_id() => "Spherical light volume mesh";

    fn spherical_light_volume_mesh_declaration() => TriangleMeshTemplate::SphericalLightVolume(
        SphericalLightVolumeMesh::new(16)
    );
}

declare_builtin_triangle_mesh! {
    /// The [`TriangleMeshID`](crate::TriangleMeshID) of a builtin mesh
    /// generated by
    /// [`TriangleMesh::create_box`](crate::TriangleMesh::create_box) with unit
    /// extents and front faces on the inside.
    fn skybox_mesh_id() => "Skybox mesh";

    fn skybox_mesh_declaration() => TriangleMeshTemplate::Box(
        BoxMesh::new(1.0, 1.0, 1.0, FrontFaceSide::Inside)
    );
}
