name: Impact CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: ${{ github.workspace }}/ci-target
  MIRI_SYSROOT: ${{ github.workspace }}/.miri-sysroot

concurrency:
  # A new push cancels any in-flight run
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

# ───────────────────────────────────────────────────────────────
# Build crates (debug + release)
# ───────────────────────────────────────────────────────────────
jobs:
  build:
    name: Build – ${{ matrix.workspace }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        workspace: [engine, roc_integration, roc_platform/core]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - workspace: roc_platform/core
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}

      - uses: dtolnay/rust-toolchain@v1
        with: { toolchain: stable, profile: minimal, override: true }

      - name: Debug build (no default features)
        working-directory: ${{ matrix.workspace }}
        run: cargo build --no-default-features

      - name: Debug build (default features)
        working-directory: ${{ matrix.workspace }}
        run: cargo build

      - name: Debug build (all features)
        working-directory: ${{ matrix.workspace }}
        run: cargo build --all-features

      - name: Release build
        working-directory: ${{ matrix.workspace }}
        run: cargo build --release

  # ───────────────────────────────────────────────────────────────
  # Build apps (debug + release)
  # ───────────────────────────────────────────────────────────────
  build_apps:
    name: Apps – ${{ matrix.workspace }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        workspace: [apps/basic_app, apps/snapshot_tester]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}

      - uses: dtolnay/rust-toolchain@v1
        with: { toolchain: stable, profile: minimal, override: true }

      - id: roc
        uses: hasnep/setup-roc@v0.5.0
        with:
          roc-version: nightly

      - name: Build (debug)
        working-directory: ${{ matrix.workspace }}
        env:
          ROC_DEBUG: "1"
          RUST_DEBUG: "1"
        run: |
          mkdir -p lib roc_platform/lib
          roc build.roc

      - name: Build (release)
        working-directory: ${{ matrix.workspace }}
        run: |
          mkdir -p lib roc_platform/lib
          roc build.roc

  # ───────────────────────────────────────────────────────────────
  # Regular tests
  # ───────────────────────────────────────────────────────────────
  test:
    name: Tests – ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        workspace: [engine]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}

      - uses: dtolnay/rust-toolchain@v1
        with: { toolchain: stable, profile: minimal, override: true }

      - name: cargo test --all-features
        working-directory: ${{ matrix.workspace }}
        run: cargo test --all-features --workspace

  # ───────────────────────────────────────────────────────────────
  # AddressSanitizer tests
  # ───────────────────────────────────────────────────────────────
  test-asan:
    name: ASan – ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        workspace: [engine]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          targets: ${{ matrix.target }}
          components: rust-src

      - name: Install ASan runtime (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y clang libclang-rt-17-dev

      - name: Test with AddressSanitizer
        working-directory: ${{ matrix.workspace }}
        env:
          ASAN_RUST_FLAGS: "-C linker=clang -Zsanitizer=address"
          RUSTFLAGS: ${{ env.ASAN_RUST_FLAGS }}
          RUSTDOCFLAGS: ${{ env.ASAN_RUST_FLAGS }}
        run: |
          cargo test --all-features --workspace --target ${{ matrix.target }}

  # ───────────────────────────────────────────────────────────────
  # Miri tests
  # ───────────────────────────────────────────────────────────────
  test-miri:
    name: Miri – ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        workspace: [engine]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}
          extra-dirs: |
            ${{ env.MIRI_SYSROOT }}

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: miri

      - name: cargo miri setup
        run: cargo miri setup

      - name: Test with Miri
        working-directory: ${{ matrix.workspace }}
        env:
          PROPTEST_DISABLE_FAILURE_PERSISTENCE: 1
          PROPTEST_CASES: 1
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-deterministic-floats"
        run: |
          cargo miri test --all-features --workspace

  # ───────────────────────────────────────────────────────────────
  # Clippy
  # ───────────────────────────────────────────────────────────────
  lint-clippy:
    name: Clippy – ${{ matrix.workspace }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        workspace:
          [
            engine,
            roc_integration,
            roc_platform/core,
            apps/basic_app,
            apps/snapshot_tester,
          ]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - workspace: roc_platform/core
            os: windows-latest
          - workspace: apps/basic_app
            os: windows-latest
          - workspace: apps/snapshot_tester
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - name: Clippy (no default features)
        working-directory: ${{ matrix.workspace }}
        run: cargo clippy --workspace --all-targets --no-default-features -- -D warnings

      - name: Clippy (default features)
        working-directory: ${{ matrix.workspace }}
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Clippy (all features)
        working-directory: ${{ matrix.workspace }}
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  # ───────────────────────────────────────────────────────────────
  # Rustfmt
  # ───────────────────────────────────────────────────────────────
  lint-fmt:
    name: Rustfmt – ${{ matrix.workspace }}
    strategy:
      fail-fast: false
      matrix:
        workspace:
          [
            engine,
            roc_integration,
            roc_platform/core,
            apps/basic_app,
            apps/snapshot_tester,
          ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt

      - name: Rustfmt
        working-directory: ${{ matrix.workspace }}
        run: cargo fmt --all -- --check

  # ───────────────────────────────────────────────────────────────
  # Docs
  # ───────────────────────────────────────────────────────────────
  docs:
    name: Docs – ${{ matrix.workspace }}
    strategy:
      fail-fast: false
      matrix:
        workspace:
          [
            engine,
            roc_integration,
            roc_platform/core,
            apps/basic_app,
            apps/snapshot_tester,
          ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}

      - uses: dtolnay/rust-toolchain@v1
        with: { toolchain: stable, profile: minimal, override: true }

      - name: cargo doc
        working-directory: ${{ matrix.workspace }}
        run: cargo doc --workspace --no-deps --document-private-items

  # ───────────────────────────────────────────────────────────────
  # Check each feature
  # ───────────────────────────────────────────────────────────────
  check-features:
    name: Features – ${{ matrix.workspace }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        workspace:
          [
            engine,
            roc_integration,
            roc_platform/core,
            apps/basic_app,
            apps/snapshot_tester,
          ]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - workspace: roc_platform/core
            os: windows-latest
          - workspace: apps/basic_app
            os: windows-latest
          - workspace: apps/snapshot_tester
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: r7kamura/rust-problem-matchers@v1

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ${{ matrix.workspace }}

      - uses: dtolnay/rust-toolchain@v1
        with: { toolchain: stable, profile: minimal, override: true }

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: cargo hack check --each-feature
        working-directory: ${{ matrix.workspace }}
        run: cargo hack check --each-feature --no-dev-deps
